username = "ubuntu"
key_file = "/home/username/.ssh/killabeez/id_ed25519.pub"
num_beez = 2
tag_name = "killabeez-test"
ssh_cidr_block = "your.ip.addr.ess/0"
vpc_id = "vpc-xxxxxxxxxxxxxxxxx"
subnet_id = "subnet-xxxxxxxxxxxxxxxxx"
security_group_id = "sg-xxxxxxxxxxxxxxxxx"
ami = "ami-xxxxxxxxxxxxxxxxx"
