tag_name = "killabeez-test"
num_beez = 2
key_file = "/home/username/.ssh/killabeez/id_ed25519.pub"
# username = "ubuntu"
# key_id = "key-xxxxxxxxxxxxxxxxx"
# ssh_cidr_block = "your.ip.addr.ess/0"
# vpc_id = "vpc-xxxxxxxxxxxxxxxxx"
# subnet_id = "subnet-xxxxxxxxxxxxxxxxx"
# security_group_id = "sg-xxxxxxxxxxxxxxxxx"
# ami = "ami-xxxxxxxxxxxxxxxxx"
